= Daikon Spring Auth
:toc:

This module provides support for Service Accounts authentication. +
It introduces `Auth0AuthenticationManager` which will validate headers populated by passthrough-auth service (Gloo) or parse Auth0 JWT itself issued for service account.
In case not all headers found and token is not SAT authentication is delegated to legacy OAuth2 authentication manager (Talend JWT or Opaque token). +
`AuthUserDetails` will be populated into SecurityContext in case of successful authentication, usages of old class `UserDetails` have to be renamed.

== Usage

. In case if you use oidc-client just update to the latest version
. If oidc-client is not used add direct dependency to daikon-spring-auth
. Update with new classes: old IdProvider interface was renamed to AuthIdProvider and oidc-client's UserDetails to AuthUserDetails

IMPORTANT: don't add direct dependency to this library while using old oidc-client version. This may cause exceptions like this one in Runtime:
           ``java.lang.ClassCastException: class org.talend.daikon.spring.sat.model.userdetails.AuthUserDetails cannot be cast to class org.talend.iam.security.userdetails.UserDetails``

== Adding dependency

To start supporting SAT it’s necessary to add the next dependency:

```xml
<dependency>
    <groupId>org.talend.daikon</groupId>
    <artifactId>daikon-spring-auth</artifactId>
    <version>${daikon.version}</version>
</dependency>
```

== Configuration

In case of using oidc-client lib no config is needed
Otherwise Auth0AuthenticationManager must be declared as Spring Component manually (see SatAutoConfiguration)
